-- 원본: docs/erd/schema.sql (테이블 정의서 v1.0). 이후 스키마 변경은 새 버전 파일로 추가한다.
-- =============================================================================
-- StoreFlow ERP 스키마 (PostgreSQL 17)
-- 기준 문서: docs/erd/01-table-definition.md, docs/erd/03-code-definition.md
-- 구현 단계에서 backend Flyway 마이그레이션(V1)의 원본으로 사용한다.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 번호 채번용 시퀀스 (판매번호 · 발주번호의 순번)
-- -----------------------------------------------------------------------------
CREATE SEQUENCE sale_number_seq;
CREATE SEQUENCE purchase_order_number_seq;

-- -----------------------------------------------------------------------------
-- roles : 역할
-- -----------------------------------------------------------------------------
CREATE TABLE roles (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    role_name       VARCHAR(20)     NOT NULL,
    description     VARCHAR(100),
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_role_name UNIQUE (role_name),
    CONSTRAINT ck_roles_role_name CHECK (role_name IN ('ADMIN', 'MANAGER', 'USER'))
);

-- -----------------------------------------------------------------------------
-- stores : 매장
-- -----------------------------------------------------------------------------
CREATE TABLE stores (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    store_code      VARCHAR(10)     NOT NULL,
    store_name      VARCHAR(50)     NOT NULL,
    address         VARCHAR(200),
    phone           VARCHAR(20),
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_stores PRIMARY KEY (id),
    CONSTRAINT uk_stores_store_code UNIQUE (store_code),
    CONSTRAINT uk_stores_store_name UNIQUE (store_name),
    CONSTRAINT ck_stores_store_code CHECK (store_code ~ '^[A-Z0-9]{2,10}$'),
    CONSTRAINT ck_stores_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- -----------------------------------------------------------------------------
-- users : 사용자
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(20)     NOT NULL,
    password        VARCHAR(100)    NOT NULL,
    name            VARCHAR(50)     NOT NULL,
    role_id         BIGINT          NOT NULL,
    store_id        BIGINT,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_users_store_id FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT ck_users_username CHECK (username ~ '^[a-z0-9]{4,20}$'),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_users_store_id ON users (store_id);

-- -----------------------------------------------------------------------------
-- categories : 카테고리
-- -----------------------------------------------------------------------------
CREATE TABLE categories (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    category_name   VARCHAR(50)     NOT NULL,
    description     VARCHAR(200),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uk_categories_category_name UNIQUE (category_name)
);

-- -----------------------------------------------------------------------------
-- products : 상품 (전 매장 공통)
-- -----------------------------------------------------------------------------
CREATE TABLE products (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    category_id     BIGINT          NOT NULL,
    product_code    VARCHAR(20)     NOT NULL,
    product_name    VARCHAR(100)    NOT NULL,
    purchase_price  BIGINT          NOT NULL,
    sale_price      BIGINT          NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uk_products_product_code UNIQUE (product_code),
    CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_products_product_code CHECK (product_code ~ '^[A-Z0-9-]{1,20}$'),
    CONSTRAINT ck_products_price CHECK (purchase_price >= 0 AND sale_price >= 0),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX idx_products_category_id ON products (category_id);

-- -----------------------------------------------------------------------------
-- suppliers : 공급처
-- -----------------------------------------------------------------------------
CREATE TABLE suppliers (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    supplier_name   VARCHAR(100)    NOT NULL,
    business_number VARCHAR(10)     NOT NULL,
    contact_name    VARCHAR(50),
    phone           VARCHAR(20),
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_suppliers PRIMARY KEY (id),
    CONSTRAINT uk_suppliers_business_number UNIQUE (business_number),
    CONSTRAINT ck_suppliers_business_number CHECK (business_number ~ '^[0-9]{10}$'),
    CONSTRAINT ck_suppliers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- -----------------------------------------------------------------------------
-- stocks : 재고 (매장 × 상품)
-- -----------------------------------------------------------------------------
CREATE TABLE stocks (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    store_id        BIGINT          NOT NULL,
    product_id      BIGINT          NOT NULL,
    quantity        INTEGER         NOT NULL DEFAULT 0,
    safety_stock    INTEGER         NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    CONSTRAINT pk_stocks PRIMARY KEY (id),
    CONSTRAINT uk_stocks_store_id_product_id UNIQUE (store_id, product_id),
    CONSTRAINT fk_stocks_store_id FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT fk_stocks_product_id FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_stocks_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT ck_stocks_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_stocks_safety_stock CHECK (safety_stock >= 0)
);
CREATE INDEX idx_stocks_product_id ON stocks (product_id);

-- -----------------------------------------------------------------------------
-- sales : 판매
-- -----------------------------------------------------------------------------
CREATE TABLE sales (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    sale_number     VARCHAR(40)     NOT NULL,
    store_id        BIGINT          NOT NULL,
    total_amount    BIGINT          NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    sold_at         TIMESTAMPTZ     NOT NULL,
    created_by      BIGINT          NOT NULL,
    cancelled_at    TIMESTAMPTZ,
    cancelled_by    BIGINT,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_sales PRIMARY KEY (id),
    CONSTRAINT uk_sales_sale_number UNIQUE (sale_number),
    CONSTRAINT fk_sales_store_id FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT fk_sales_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_sales_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id),
    CONSTRAINT ck_sales_total_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_sales_status CHECK (
        (status = 'COMPLETED' AND cancelled_at IS NULL AND cancelled_by IS NULL) OR
        (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL)
    )
);
CREATE INDEX idx_sales_store_id_sold_at ON sales (store_id, sold_at);
CREATE INDEX idx_sales_sold_at ON sales (sold_at);

-- -----------------------------------------------------------------------------
-- sale_items : 판매 상세
-- -----------------------------------------------------------------------------
CREATE TABLE sale_items (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    sale_id         BIGINT          NOT NULL,
    product_id      BIGINT          NOT NULL,
    quantity        INTEGER         NOT NULL,
    unit_price      BIGINT          NOT NULL,
    total_price     BIGINT          NOT NULL,
    CONSTRAINT pk_sale_items PRIMARY KEY (id),
    CONSTRAINT uk_sale_items_sale_id_product_id UNIQUE (sale_id, product_id),
    CONSTRAINT fk_sale_items_sale_id FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sale_items_product_id FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_sale_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sale_items_price CHECK (unit_price >= 0 AND total_price = unit_price * quantity)
);
CREATE INDEX idx_sale_items_product_id ON sale_items (product_id);

-- -----------------------------------------------------------------------------
-- purchase_orders : 발주
-- -----------------------------------------------------------------------------
CREATE TABLE purchase_orders (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    order_number    VARCHAR(40)     NOT NULL,
    store_id        BIGINT          NOT NULL,
    supplier_id     BIGINT          NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    total_amount    BIGINT          NOT NULL,
    ordered_at      TIMESTAMPTZ     NOT NULL,
    created_by      BIGINT          NOT NULL,
    approved_at     TIMESTAMPTZ,
    approved_by     BIGINT,
    completed_at    TIMESTAMPTZ,
    completed_by    BIGINT,
    cancelled_at    TIMESTAMPTZ,
    cancelled_by    BIGINT,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id),
    CONSTRAINT uk_purchase_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_purchase_orders_store_id FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT fk_purchase_orders_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_purchase_orders_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_purchase_orders_approved_by FOREIGN KEY (approved_by) REFERENCES users (id),
    CONSTRAINT fk_purchase_orders_completed_by FOREIGN KEY (completed_by) REFERENCES users (id),
    CONSTRAINT fk_purchase_orders_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id),
    CONSTRAINT fk_purchase_orders_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT ck_purchase_orders_total_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_purchase_orders_processor CHECK (
        (approved_at IS NULL) = (approved_by IS NULL) AND
        (completed_at IS NULL) = (completed_by IS NULL) AND
        (cancelled_at IS NULL) = (cancelled_by IS NULL)
    ),
    CONSTRAINT ck_purchase_orders_status CHECK (
        (status = 'DRAFT'     AND approved_at IS NULL     AND completed_at IS NULL     AND cancelled_at IS NULL) OR
        (status = 'APPROVED'  AND approved_at IS NOT NULL AND completed_at IS NULL     AND cancelled_at IS NULL) OR
        (status = 'COMPLETED' AND approved_at IS NOT NULL AND completed_at IS NOT NULL AND cancelled_at IS NULL) OR
        (status = 'CANCELLED' AND completed_at IS NULL    AND cancelled_at IS NOT NULL)
    )
);
CREATE INDEX idx_purchase_orders_store_id_ordered_at ON purchase_orders (store_id, ordered_at);
CREATE INDEX idx_purchase_orders_ordered_at ON purchase_orders (ordered_at);
CREATE INDEX idx_purchase_orders_supplier_id ON purchase_orders (supplier_id);

-- -----------------------------------------------------------------------------
-- purchase_order_items : 발주 상세
-- -----------------------------------------------------------------------------
CREATE TABLE purchase_order_items (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id   BIGINT      NOT NULL,
    product_id          BIGINT      NOT NULL,
    quantity            INTEGER     NOT NULL,
    unit_price          BIGINT      NOT NULL,
    total_price         BIGINT      NOT NULL,
    CONSTRAINT pk_purchase_order_items PRIMARY KEY (id),
    CONSTRAINT uk_purchase_order_items_purchase_order_id_product_id UNIQUE (purchase_order_id, product_id),
    CONSTRAINT fk_purchase_order_items_purchase_order_id FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_purchase_order_items_product_id FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_purchase_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_purchase_order_items_price CHECK (unit_price >= 0 AND total_price = unit_price * quantity)
);
CREATE INDEX idx_purchase_order_items_product_id ON purchase_order_items (product_id);

-- -----------------------------------------------------------------------------
-- stock_histories : 재고 이력 (수정 · 삭제 없음)
-- -----------------------------------------------------------------------------
CREATE TABLE stock_histories (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    store_id        BIGINT          NOT NULL,
    product_id      BIGINT          NOT NULL,
    type            VARCHAR(20)     NOT NULL,
    quantity        INTEGER         NOT NULL,
    before_quantity INTEGER         NOT NULL,
    after_quantity  INTEGER         NOT NULL,
    reference_type  VARCHAR(20),
    reference_id    BIGINT,
    reason          VARCHAR(200),
    created_by      BIGINT          NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT pk_stock_histories PRIMARY KEY (id),
    CONSTRAINT fk_stock_histories_store_id FOREIGN KEY (store_id) REFERENCES stores (id),
    CONSTRAINT fk_stock_histories_product_id FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_stock_histories_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_stock_histories_quantity CHECK (
        quantity <> 0 AND
        before_quantity >= 0 AND
        after_quantity >= 0 AND
        after_quantity = before_quantity + quantity
    ),
    CONSTRAINT ck_stock_histories_type CHECK (
        (type = 'SALE'        AND quantity < 0 AND reference_type = 'SALE'           AND reference_id IS NOT NULL) OR
        (type = 'SALE_CANCEL' AND quantity > 0 AND reference_type = 'SALE'           AND reference_id IS NOT NULL) OR
        (type = 'PURCHASE'    AND quantity > 0 AND reference_type = 'PURCHASE_ORDER' AND reference_id IS NOT NULL) OR
        (type = 'ADJUSTMENT'  AND reference_type IS NULL AND reference_id IS NULL AND reason IS NOT NULL)
    )
);
CREATE INDEX idx_stock_histories_store_id_product_id_created_at ON stock_histories (store_id, product_id, created_at);
CREATE INDEX idx_stock_histories_created_at ON stock_histories (created_at);
CREATE INDEX idx_stock_histories_reference ON stock_histories (reference_type, reference_id);

-- -----------------------------------------------------------------------------
-- 초기 데이터 : 역할
-- -----------------------------------------------------------------------------
INSERT INTO roles (role_name, description) VALUES
    ('ADMIN',   '본사 관리자'),
    ('MANAGER', '매장 관리자'),
    ('USER',    '매장 직원');
